### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Dmitry221060**
Removes a billion standard libraries that were uploaded for some reason
Removes both custom packages(NAudio and Lidgren) since they were not used
Removes unused(Legacy?) socket networking classes
Removes ModLauncher 
Removes calls of overridden virtual methods from mod system(they do nothing and are not supposed to be called) 
Removes excessive custom assembly metadata in server mod system
Removes ".src" from some namespaces as it was generated by Visual Studio and is a bad way to manage namespaces
Optimizes project file
Changes all project imports/paths from hardcoded values to use environment variable VINTAGE_STORY, according to modding guidelines and a template mod
Explicitly defines events in Network classes by adding the `event` keyword
Minor code style changes in Network classes
Updates version to 1.2.1

### CODE REVIEW

**Comment by blakdragan7** [comment]
"Removes unused(Legacy?) socket networking classes" this was being kept in case the built in network was to slow

**Comment by blakdragan7** [comment]
honestly though, it should probably be re-written anyway

**Comment by Dmitry221060** [comment]
> "Removes unused(Legacy?) socket networking classes" this was being kept in case the built in network was to slow

It stays in the git history so if we ever need it back it will be easy to restore. No need to keep a local copy

**Comment by blakdragan7** [comment]
> It stays in the git history so if we ever need it back it will be easy to restore. No need to keep a local copy
True.

**Pull request merged**
